---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(dplyr)
library(tidyverse)
```


```{r}
aux_tomato_sano_regulador<-read.csv("../data/Auxin_regulatoryNetwork_healthy.tsv", header=F, sep='\t')
bra_tomato_sano_regulador<-read.csv("../data/Brassinos_regulatoryNetwork_healthy.tsv", header=F, sep='\t')
MYC2_tomato_sano_regulador<-read.csv("../data/MYC2_regulatoryNetwork_healthy.tsv", header=F, sep='\t')

families <- read.csv("../data/Sly_TF_list.txt", header=TRUE, sep='\t') %>%
  select(-1) %>% 
  mutate(across(everything(), ~ str_replace(., "\\.\\d+$", "")))
families

dict_fam<-setNames(families$Family,families$Gene_ID)
str(dict_fam)

dict_fam

aux_tomato_sano_regulador_fam<-aux_tomato_sano_regulador%>%
  mutate(FT = recode(V1, !!!dict_fam, .default = "none")) %>%
  rename(regulador = V1,
         estado_1 = V2,
         regulon = V3,
         estado_2 = V4
         )


bra_tomato_sano_regulador_fam<-bra_tomato_sano_regulador%>%
  mutate(FT = recode(V1, !!!dict_fam, .default = "none")) %>%
  rename(regulador = V1,
         estado_1 = V2,
         regulon = V3,
         estado_2 = V4
         )

MYC2_tomato_sano_regulador_fam<-MYC2_tomato_sano_regulador%>%
  mutate(FT = recode(V1, !!!dict_fam, .default = "none")) %>%
  rename(regulador = V1,
         estado_1 = V2,
         regulon = V3,
         estado_2 = V4
         )

aux_tomato_sano_regulador_fam
bra_tomato_sano_regulador_fam
MYC2_tomato_sano_regulador_fam



write.table(aux_tomato_sano_regulador_fam, "../output-files/Auxin_regulatoryNetwork_healthy_fam.tsv", 
            sep = "\t", row.names = FALSE, col.names=TRUE, quote = FALSE)
write.table(bra_tomato_sano_regulador_fam, "../output-files/Brassinos_regulatoryNetwork_healthy_fam.tsv", 
            sep = "\t", row.names = FALSE, col.names=TRUE, quote = FALSE)
write.table(MYC2_tomato_sano_regulador_fam, "../output-files/MYC2_regulatoryNetwork_healthy_fam.tsv", 
            sep = "\t", row.names = FALSE, col.names=TRUE, quote = FALSE)

```
